# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: true
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia -e 'Pkg.add("Nemo")'
- julia -e 'Pkg.add("Memoize")'
- julia -e 'Pkg.add("HTTP")'
- julia -e 'Pkg.add("OffsetArrays")'
- julia -e 'Pkg.add("IterTools")'
- julia -e 'Pkg.clone(pwd())'
- julia -e 'Pkg.build("MathIntSeq")'
- julia -e 'Pkg.test("MathIntSeq"; coverage=false)'
