environment:
  matrix:
    - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"
    - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"

matrix:
  allow_failures:
    - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"

branches:
  only:
    - master

notifications:
    - provider: Email
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: true

install:
# Download most recent Julia Windows binary
    - ps: (new-object net.webclient).DownloadFile(
          $env:JULIA_URL,
          "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
    - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
    - IF EXIST .git\shallow (git fetch --unshallow)
    - C:\projects\julia\bin\julia -e "versioninfo();
      Pkg.add(\"Nemo\");
      Pkg.add(\"Memoize\");
      Pkg.add(\"HTTP\");
      Pkg.add(\"OffsetArrays\");
      Pkg.add(\"IterTool\");
      Pkg.clone(pwd(), \"MathIntSeq\");
      Pkg.build(\"MathIntSeq\")"

test_script:
    - C:\projects\julia\bin\julia -e "Pkg.test(\"MathIntSeq\")"
